version: "3.5"

services:
  api01: &api01
    image: avinho/rinhabackend:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3001:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "125MB"
    networks:
      - rinha-network

  api02:
    <<: *api01
    hostname: api02
    ports:
      - "3002:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
    networks:
      - rinha-network

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql
    command: 'postgres -c autovacuum=on -c wal_compression=on -c effective_cache_size=8GB -c max_connections=300 -c synchronous_commit=off -c checkpoint_timeout=6000 -c full_page_writes=off'
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "250MB"
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "rinha", "-U", "admin"]
      interval: 40s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rinha-network:
    driver: bridge